Olympus-HPC/proteus

- .github/workflows/ci-build-test.yml
- .gitignore
- .gitlab-ci.yml
- .gitlab/custom-jobs-and-variables.yml
- .gitlab/jobs/lassen.yml
- .gitlab/jobs/tioga.yml
- .gitlab/subscribed-pipelines.yml
- CMakeLists.txt
- lib/CMakeLists.txt
- scripts/gitlab/ci-build-test.sh
- tests/CMakeLists.txt
> Add github and gitlab ci

- .github/workflows/check-clang-format.yml
Add a workflow to check formatting using clang-format
Closes #21
> Check style with clang-format in CI

- README.md
> Update README to include CMake instructions

- scripts/gitlab/ci-build-test.sh
Use tmp to work around frequent NFS issues
> Use tmp for gitlab ci

- .gitlab/custom-jobs-and-variables.yml
> Speed up tioga testing

- common/Logger.hpp
> Add getpid() call to log name

- lib/JitEngineDevice.hpp
> Simplify and make more robust RDC IR linking

- lib/JitEngineDevice.hpp
- lib/JitEngineDeviceCUDA.hpp
- lib/JitEngineDeviceHIP.hpp
> Detects AMD Thread/Block/Grid Dim intrinsics and specializes with them

- .gitlab-ci.yml
- .gitlab/custom-jobs-and-variables.yml
- .gitlab/jobs/lassen-benchmarks.yml
- .gitlab/jobs/tioga-benchmarks.yml
- .gitlab/subscribed-pipelines.yml
- scripts/gitlab/ci-run-benchmarks.sh
* Run benchmarks in gitlab CI toggled by `/run-benchmarks` in comments
* Collect artifacts in gitlab (CSV files and plots)
* Upload plot artifacts in github
> Run proteus benchmarks on gitlab CI

- .github/workflows/cpp-linter.yml
Reduce the verbosity of `cpp-linter`
> Update cpp-linter to reduce verbosity

- lib/CompilerInterfaceDeviceInternal.hpp
- lib/JitEngine.cpp
- lib/JitEngine.hpp
- lib/JitEngineDevice.hpp
- Disable proteus through the env var ENV_PROTEUS_DISABLE
- Execute the original kernel code if disabled
> Disable proteus through env var

- .gitlab-ci.yml
- .gitlab/jobs/tioga-integration.yml
- .gitlab/subscribed-pipelines.yml
- tests/integration/hip/ci-test-integration.sh
- tests/integration/hip/cmake-shared_libs-shared_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_libs-shared_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-shared_libs-shared_proteus/libbar.cpp
- tests/integration/hip/cmake-shared_libs-shared_proteus/libfoo.cpp
- tests/integration/hip/cmake-shared_libs-shared_proteus/main.cpp
- tests/integration/hip/cmake-shared_libs-static_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_libs-static_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-shared_libs-static_proteus/libbar.cpp
- tests/integration/hip/cmake-shared_libs-static_proteus/libfoo.cpp
- tests/integration/hip/cmake-shared_libs-static_proteus/main.cpp
- tests/integration/hip/cmake-shared_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-shared_proteus/main.cpp
- tests/integration/hip/cmake-static_proteus/CMakeLists.txt
- tests/integration/hip/cmake-static_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-static_proteus/main.cpp
- tests/integration/hip/make-shared_proteus/Makefile
- tests/integration/hip/make-shared_proteus/ci-build-and-run.sh
- tests/integration/hip/make-shared_proteus/main.cpp
- tests/integration/hip/make-static_proteus/Makefile
- tests/integration/hip/make-static_proteus/ci-build-and-run.sh
- tests/integration/hip/make-static_proteus/main.cpp
Add integration tests for several use cases testing static/shared libproteus integration:
- cmake
- cmake with shared libs
- make
> Add integration tests for HIP

- lib/CMakeLists.txt
- lib/CompilerInterfaceDeviceInternal.hpp
- lib/CoreDevice.hpp
- lib/CoreDeviceCUDA.hpp
- lib/CoreDeviceHIP.hpp
- lib/JitEngineDevice.hpp
- lib/JitEngineDeviceCUDA.cpp
- lib/JitEngineDeviceCUDA.hpp
- lib/JitEngineDeviceHIP.cpp
- lib/JitEngineDeviceHIP.hpp
Avoid the overhead looking into the KernelInfo map if proteus is disabled
> Make the code path with disabled proteus faster

- include/proteus/JitEngineDevice.hpp
- src/lib/JitEngineDeviceHIP.cpp
- Use LTO code for importing undefined globals at JIT linking, instead of replacing per TU module extracted bitcode. LTO includes code post-optimization, which blocks proteus specialization (e.g., due to inlining) if used as the JIT module.
> Update HIP LTO handling to unblock specialization

- src/lib/CMakeLists.txt
- tests/integration/hip/cmake-shared_libs-shared_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_libs-shared_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-shared_libs-static_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_libs-static_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-shared_proteus/CMakeLists.txt
- tests/integration/hip/cmake-shared_proteus/ci-build-and-run.sh
- tests/integration/hip/cmake-static_proteus/CMakeLists.txt
- tests/integration/hip/cmake-static_proteus/ci-build-and-run.sh
Also update integration tests to run from the installation directory too
> Export link dirs in the proteus lib cmake

- include/proteus/CompilerInterfaceDeviceInternal.hpp
- include/proteus/JitEngine.hpp
- include/proteus/JitEngineDevice.hpp
- scripts/gitlab/ci-build-test.sh
- scripts/gitlab/ci-run-benchmarks.sh
- src/lib/JitEngine.cpp
- src/lib/JitEngineDeviceCUDA.cpp
- src/lib/JitEngineDeviceHIP.cpp
> [Refactor] Remove ENV prefix from proteus env vars

- include/proteus/CoreLLVMCUDA.hpp
> Fix for LLVM 18 in CUDA proteus

- include/proteus/CoreLLVMDevice.hpp
- include/proteus/Logger.hpp
- src/lib/JitEngineHost.cpp
- Move modules to files instead of the output stream
> Add logfile method to Logger to store modules

- CMakeLists.txt
- include/proteus/CompilerAsync.hpp
- include/proteus/CompilerInterfaceDeviceInternal.hpp
- include/proteus/CoreLLVMCUDA.hpp
- include/proteus/CoreLLVMDevice.hpp
- include/proteus/CoreLLVMHIP.hpp
- include/proteus/Hashing.hpp
- include/proteus/JitCache.hpp
- include/proteus/JitEngineDevice.hpp
- include/proteus/JitEngineHost.hpp
- include/proteus/TransformArgumentSpecialization.hpp
- include/proteus/TransformLambdaSpecialization.hpp
- src/lib/JitEngine.cpp
- src/lib/JitEngineDeviceCUDA.cpp
- src/lib/JitEngineDeviceHIP.cpp
- src/lib/JitEngineHost.cpp
- src/pass/ProteusPass.cpp
* Add `-Wall -Wextra` as developer options in the cmake
* Fix most of the reported warnings
NFC = No Functionality Change (expected)
> [NFC] Add warnings as cmake dev options and fix

- src/lib/JitEngineDeviceCUDA.cpp
- src/lib/JitEngineDeviceHIP.cpp
- src/lib/JitEngineHost.cpp
- Reduce overhead of parsing IR on as-needed basis for creating JIT modules
> Parse IR lazily

- include/proteus/Config.hpp
- include/proteus/CoreLLVM.hpp
- include/proteus/CoreLLVMCUDA.hpp
- include/proteus/CoreLLVMDevice.hpp
- include/proteus/CoreLLVMHIP.hpp
- include/proteus/JitEngine.hpp
- include/proteus/JitEngineDevice.hpp
- include/proteus/Logger.hpp
- include/proteus/TimeTracing.hpp
- src/lib/CMakeLists.txt
- src/lib/JitEngine.cpp
- src/lib/JitEngineDeviceCUDA.cpp
- src/lib/JitEngineDeviceHIP.cpp
- src/lib/JitEngineHost.cpp
This PR adds logging to console with timers on the components of compiling a kernel.
> Update logging for console output and timers

- include/proteus/CoreLLVMHIP.hpp
LLVM 18 IR includes these functions for GPU dims
> Add new HIP functions for dims specialization

- include/proteus/CoreLLVMDevice.hpp
- include/proteus/JitEngineDevice.hpp
- Support also the non-lightweight case
- Store the post-internalization and cleanup module and bitcode
> Move kernel bitcode creation to engine

- src/pass/ProteusPass.cpp
- Avoid definitions in per-TU extracted modules, unnecessary global variables, and strip debug info
> Prune the HIP LTO module extracted in pass

- include/proteus/JitInterface.hpp
- src/pass/ProteusPass.cpp
- Avoid errors when compiling with O0
- Make the interface more robust
> Fix proteus::jit_arg analysis and instrumentation
