lib/JitEngineHost.cpp
- LLVM built with assertions on will abort if the error of the Expected value is not handled.
=> Fix LLVM internal assertion for host-device JIT

cmake/proteusConfig.cmake.in
Support easily integrating proteus in a cmake project using the `add_proteus` function. Avoids linking errors when included ProteusPass as a linked library (thanks @tbennun)
=> Create add_proteus cmake function for importing

common/Logger.hpp, lib/CompilerInterfaceDeviceInternal.hpp, lib/CompilerInterfaceHost.cpp, lib/JitEngine.cpp, lib/JitEngineDevice.hpp, lib/JitEngineDeviceCUDA.cpp, lib/JitEngineDeviceHIP.cpp, lib/JitEngineHost.cpp, lib/TransformArgumentSpecialization.hpp, lib/TransformLambdaSpecialization.hpp, lib/Utils.h, pass/ProteusPass.cpp
Store debug output in files
Closes #24
=> Add Logger for file output logs

tests/cpu/CMakeLists.txt, tests/gpu/CMakeLists.txt
- Replace CMAKE_SOURCE_DIR in OBJECT_DEPENDS with PROJECT_SOURCE_DIR for git submodule deployment
- Remove linkings with ProteusPass
Closes #71
=> Sanitize cmake files for tests

lib/JitEngineDevice.hpp, pass/ProteusPass.cpp, tests/gpu/CMakeLists.txt, tests/gpu/file1_kernel_launcher.cpp, tests/gpu/file2_kernel_launcher.cpp, tests/gpu/gpu_common.h, tests/gpu/launcher.hpp
- Add test `multi_file_launcher`
- Fix by removing overconservative fatal errors
=> Fix multiple annotations with RDC

lib/CompilerInterfaceTypes.h, pass/CMakeLists.txt, pass/GenRuntimeConstantTy.hpp, pass/ProteusPass.cpp
- Use cmake to generate LLVM IR for the RuntimeConstant type
- Generate the RuntimeConstantTy in Proteuss pass using the generated LLVM IR
- Avoid errors between the pass-library interface  due to platform specific padding, alignment, and long double implementation
=> Sync RuntimeConstantTy between pass and runtime

lib/JitEngineDevice.hpp, lib/JitEngineDeviceCUDA.cpp, lib/JitEngineDeviceCUDA.hpp, lib/JitEngineDeviceHIP.cpp, lib/JitEngineDeviceHIP.hpp
Avoid re-parsing the bitcode in a memory buffer. Store linked IR modules in the kernel info map.
=> Extract device bitcode once optimization

scripts/gitlab/ci-run-benchmarks.sh
- Fix check for PR to avoid running on merge
- Fix the version of `proteus-benchmarks` to clone using a tag
=> Run benchmarks only in PRs and use tagged version

lib/JitEngineDevice.hpp
Fix performance regression that causes `optimizeIR` *not* to run for CUDA. Continuous benchmarking detected this case.
=> Fix running optimizeIR for CUDA

cmake/proteusConfig.cmake.in
Before this PR, systems with built-in lld would link to the incorrect version, leading to incompatibilities during runtime.
=> Fix CMake config linking external projects with incorrect LLVM/LLD

src/lib/JitEngineDeviceHIP.cpp, tests/cpu/CMakeLists.txt, tests/gpu/CMakeLists.txt
- Fix object buffer bug, deleting backing temp file
- Add no-undefined to lld to detect linking errors
- Fix testing to forward env vars through lit
=> Fix alternative HIP codegen

src/pass/ProteusPass.cpp, tests/gpu/lambda.cpp
Loosen demangled name matching strictness to handle lambda launchers with arguments and print demangled name if check fails. Previously I'd get errors for something like the following for `... void kernel(int n, T LB)`:
`
fatal error: error in backend: .../proteus/src/pass/ProteusPass.cpp:266 => .../proteus/src/pass/ProteusPass.cpp:263 => Expected the annotated Fn _ZZ4mainENKUliE_clEi (main::'lambda'(int)::operator()(int) const) to be a kernel function or device lambda function!
`
I also added an example to the gpu lambda test.
=> Fix type matching for lambdas with arguments 

include/proteus/JitEngineDevice.hpp
- Use STL std::unordered_map instead of LLVM ADT DenseMap (which is unsafe during static initialization) to avoid memory corruption
=> Fix segfault from unsafe DenseMap in global constructor

cmake/proteusConfig.cmake.in
This PR is necessary for projects with multiple dependent targets, in order for it not link with LLVM more than once.
=> Do not propagate static library linkage

CMakeLists.txt, cmake/ProteusFunctions.cmake, cmake/proteusConfig.cmake.in
note: I still want to add an integration test of this
=> feature: change CMake so add_proteus is callable from a project using proteus as a submodule

scripts/gitlab/ci-build-test.sh
- Run build tests for all configurations as before
- Run ctests only for the "production" configurations (no debug output, no time tracing)
=> Simplify testing for speed

include/proteus/CoreLLVMDevice.hpp, include/proteus/JitEngineDevice.hpp
This provides a significant (2x) speedup in a large application using Proteus
=> Cache CallGraph in BinaryInfo

include/proteus/CompilationTask.hpp, include/proteus/CoreLLVMDevice.hpp, include/proteus/JitEngineDevice.hpp, src/lib/JitEngineDeviceCUDA.cpp, src/lib/JitEngineDeviceHIP.cpp
Both LLVMContext and Module are not thread-safe. Concurrent lazy parsing happens in our async compilation which creates concurrency bugs. This PR create a separate owning context per different persistent modules (i.e., BinInfo's ExtractedModule and unspecialized KernelInfo's KernelModule). Also, stores and uses the Kernel Bitcode which is the common idiom in LLVM for thread-safe processing by cloning a Module in a different context.
=> Fix lazy parsing with per module contexts

include/proteus/CompilationTask.hpp, include/proteus/CompilerInterfaceTypes.h, include/proteus/CoreLLVMDevice.hpp, include/proteus/Hashing.hpp, include/proteus/JitCache.hpp, include/proteus/JitEngine.hpp, include/proteus/JitEngineDevice.hpp, include/proteus/JitEngineHost.hpp, include/proteus/TransformArgumentSpecialization.hpp, src/lib/CMakeLists.txt, src/lib/CompilerInterfaceDevice.cpp, src/lib/CompilerInterfaceHost.cpp, src/lib/CompilerInterfaceRuntimeConstantInfo.cpp, src/lib/JitEngine.cpp, src/lib/JitEngineHost.cpp, src/pass/ProteusPass.cpp
- Introduce __proteus_create_runtime_constant_info to create runtime constant info and manage memory in the runtime library
- Initialize array of runtime constant info pointers once in the pass and provide to the runtime library
- Update the runtime library to use the runtime constant info pointer array to create vector of RuntimeConstant objects with values extracted at runtime
**More information**
The previous interface requires the pass to create 1D arrays of runtime constant info (types, indices) which is quite cumbersome to extend, especially if the metadata information is sparse and does not apply to all runtime constants. This change sets up creating the `proteus::jit_array` interface that will enable specializing for arrays of scalars.
=> Refactor interface for runtime constant info

include/proteus/CppJitModule.hpp, include/proteus/Frontend/Dispatcher.hpp, include/proteus/Frontend/DispatcherCUDA.hpp, include/proteus/Frontend/DispatcherHIP.hpp, include/proteus/Frontend/DispatcherHost.hpp, include/proteus/JitFrontend.hpp, tests/frontend/cpu/cpp_source.cpp, tests/frontend/gpu/cpp_adam.cpp, tests/frontend/gpu/cpp_instantiate.cpp, tests/frontend/gpu/cpp_source.cpp, tests/integration/hip/cmake-clang_plugin-proteusFrontend/main.cpp, tests/integration/hip/cmake-proteusFrontend/main.cpp
- Add typed KernelHandle, FunctionHandle stateful objects that cache the function pointer avoiding cache lookups by function name
- Introduce type checking requiring the function signature in run, launch interfaces
=> [cpp-frontend] Add more type checking and reduce overhead

src/lib/Frontend/CppJitModule.cpp
- Change to O1 in compileCppToIR to avoid optimization blockers to the JIT engine, e.g., O0 adds noinline which we can't remove easily like optnone.
- Change to O3 in compileCppToDynamicLibrary to maximize optimization by default since producing a binary
Either way those can be overriden by the user using the ExtraArgs interface.
=> [cpp-frontend] Update default optimization levels

include/proteus/Frontend/DispatcherCUDA.hpp, include/proteus/Frontend/DispatcherHIP.hpp
- Remove [[maybe_unused]] from Ctx in the compile() method and move Ctx, Mod to owners to ensure context destroys after module
=> Fix lifetime bug in device dispatchers

src/lib/JitEngineHost.cpp, src/pass/ProteusPass.cpp, tests/cpu/CMakeLists.txt
- Do not change linkage and visibility in the original module's symbols
- Remove duplicate check for unresolved symbols in the LLVM IR
- Link consumer tests with `-rdynamic` (as we document)
=> Fix linking bug with proteus and non-proteus compiled objects

src/lib/Frontend/Func.cpp, tests/frontend/cpu/add_vectors.cpp, tests/frontend/gpu/adam.cpp, tests/frontend/gpu/adam_runconst.cpp, tests/frontend/gpu/add_vectors.cpp
Since v14, clang sets the flag [`-ffp-contract=on`](https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#floating-point-support-in-clang) by default, enabling IR instruction rewrites into FMA.
By setting this flag in PJ-DSL's IRBuilder, we match Clang's default behavior, which the CPP and annotation JIT frontends both use.
This improves PJ-DSL performance, eliminating most of its slowdown relative to the other frontends (remaining slowdown is attributed to no launch bound specialization).
GEMM (HIP, Tuolumne) without fp-contract:
```
Average over 25 trials: 89.928 ms
```
GEMM (HIP, Tuolumne) with fp-contract:
```
Average over 25 trials: 83.211 ms
```
One value in the `adam` tests changes as a result. FMA is generally considered more accurate than the unfused multiply + add …
=> PJ-DSL: Turn fp-contract on

include/proteus/Frontend/Func.hpp, include/proteus/JitFrontend.hpp, tests/frontend/cpu/add_vectors.cpp, tests/frontend/cpu/add_vectors_runconst.cpp, tests/frontend/cpu/array.cpp, tests/frontend/cpu/external_call.cpp, tests/frontend/cpu/for.cpp, tests/frontend/cpu/if.cpp, tests/frontend/cpu/internal_call.cpp, tests/frontend/cpu/loopnest_1d.cpp, tests/frontend/cpu/loopnest_3d.cpp, tests/frontend/cpu/loopnest_3d_uniformtile.cpp, tests/frontend/cpu/min.cpp, tests/frontend/cpu/multi_module.cpp, tests/frontend/cpu/operators.cpp, tests/frontend/cpu/tiled_matmul.cpp, tests/frontend/cpu/tiled_transpose.cpp, tests/frontend/gpu/adam.cpp, tests/frontend/gpu/adam_runconst.cpp, tests/frontend/gpu/add_vectors.cpp, tests/frontend/gpu/add_vectors_runconst.cpp, tests/frontend/gpu/floydwarshall.cpp, tests/frontend/gpu/for.cpp, tests/frontend/gpu/if.cpp, tests/frontend/gpu/internal_call.cpp, tests/frontend/gpu/kernel_2d.cpp, tests/frontend/gpu/kernel_3d.cpp, tests/frontend/gpu/multi_module.cpp, tests/frontend/gpu/operators.cpp, tests/frontend/gpu/shared_memory.cpp
This PR adds function arguments to PJ-DSL for external and internal functions. It also brings PJ-DSL `addFunction`/`addKernel` syntax in line with CPPJitModule.
```c++
auto &F = J->addFunction<void(int)>("function");
...
auto &V3 = F.call<int(int, int)>("add", V1, V2);
```
The function's signature is repeated at callsites so internal/external functions maintain the same interface.
=> PJ-DSL: Call Functions with Args

cmake/SetupLLVM.cmake, cmake/proteusConfig.cmake.in, tests/integration/hip/ci-test-integration.sh
Fixes an issue where CMake reports a mismatch between
/opt/rocm-6.3.1/llvm/lib/cmake/llvm
/opt/rocm-6.3.1/llvm//lib/cmake/llvm
Although these point to the same directory, the redundant "//"
causes Proteus to treat them as different. This patch normalizes
LLVM_DIR paths before comparison.
Note: /opt/rocm-6.3.1/llvm is a symlink to /opt/rocm-6.3.1/lib/llvm,
so projects that integrate with Proteus (e.g. Mneme) must also
resolve LLVM_DIR consistently.
=> Set LLVM_DIR to real path

src/lib/Frontend/Var.cpp, tests/frontend/cpu/operators.cpp, tests/frontend/gpu/operators.cpp
The implementations for Var's scalar constant `-=` and `<=` use the wrong operation.
This fixes that and adds tests for these operations; the tests fail without the changes to Var.cpp.
=> PJ-DSL: Fix operator bugs
